# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'index.ui'
#
# Created by: PyQt5 UI code generator 5.4.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Index_UI(object):
    def setupUi(self, Index_UI):
        Index_UI.setObjectName("Index_UI")
        Index_UI.resize(800, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Index_UI.sizePolicy().hasHeightForWidth())
        Index_UI.setSizePolicy(sizePolicy)
        Index_UI.setAutoFillBackground(False)
        Index_UI.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(Index_UI)
        self.centralwidget.setObjectName("centralwidget")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(510, 530, 272, 41))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(50, 30, 705, 531))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_2.setVerticalSpacing(15)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, -1, 3, -1)
        self.horizontalLayout.setSpacing(20)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("FreeMono")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(134, 134, 134);")
        self.label.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label.setLineWidth(10)
        self.label.setMidLineWidth(10)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.menu = QtWidgets.QTreeWidget(self.gridLayoutWidget)
        self.menu.setAutoFillBackground(True)
        self.menu.setStyleSheet("")
        self.menu.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.menu.setFrameShadow(QtWidgets.QFrame.Plain)
        self.menu.setLineWidth(1)
        self.menu.setAutoScroll(False)
        self.menu.setTabKeyNavigation(False)
        self.menu.setProperty("showDropIndicator", True)
        self.menu.setAlternatingRowColors(True)
        self.menu.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.menu.setTextElideMode(QtCore.Qt.ElideRight)
        self.menu.setAutoExpandDelay(1)
        self.menu.setRootIsDecorated(False)
        self.menu.setItemsExpandable(True)
        self.menu.setAnimated(True)
        self.menu.setAllColumnsShowFocus(True)
        self.menu.setHeaderHidden(True)
        self.menu.setObjectName("menu")
        item_0 = QtWidgets.QTreeWidgetItem(self.menu)
        font = QtGui.QFont()
        font.setFamily("Waree")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        item_0.setFont(0, font)
        brush = QtGui.QBrush(QtGui.QColor(6, 6, 6))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item_0.setBackground(0, brush)
        brush = QtGui.QBrush(QtGui.QColor(249, 249, 249))
        brush.setStyle(QtCore.Qt.NoBrush)
        item_0.setForeground(0, brush)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(True)
        item_1.setFont(0, font)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(True)
        item_1.setFont(0, font)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(True)
        item_1.setFont(0, font)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(True)
        item_1.setFont(0, font)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(True)
        item_1.setFont(0, font)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(True)
        item_1.setFont(0, font)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(True)
        item_1.setFont(0, font)
        item_0 = QtWidgets.QTreeWidgetItem(self.menu)
        font = QtGui.QFont()
        font.setFamily("Waree")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        item_0.setFont(0, font)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item_0.setBackground(0, brush)
        brush = QtGui.QBrush(QtGui.QColor(245, 245, 245))
        brush.setStyle(QtCore.Qt.NoBrush)
        item_0.setForeground(0, brush)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(True)
        item_1.setFont(0, font)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(True)
        item_1.setFont(0, font)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(True)
        item_1.setFont(0, font)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(True)
        item_1.setFont(0, font)
        item_0 = QtWidgets.QTreeWidgetItem(self.menu)
        font = QtGui.QFont()
        font.setFamily("Waree")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        item_0.setFont(0, font)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item_0.setBackground(0, brush)
        brush = QtGui.QBrush(QtGui.QColor(248, 248, 248))
        brush.setStyle(QtCore.Qt.NoBrush)
        item_0.setForeground(0, brush)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(True)
        item_1.setFont(0, font)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(True)
        item_1.setFont(0, font)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(True)
        item_1.setFont(0, font)
        item_0 = QtWidgets.QTreeWidgetItem(self.menu)
        font = QtGui.QFont()
        font.setFamily("Waree")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        item_0.setFont(0, font)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item_0.setBackground(0, brush)
        brush = QtGui.QBrush(QtGui.QColor(250, 250, 250))
        brush.setStyle(QtCore.Qt.NoBrush)
        item_0.setForeground(0, brush)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(True)
        item_1.setFont(0, font)
        self.menu.header().setVisible(False)
        self.menu.header().setStretchLastSection(True)
        self.verticalLayout.addWidget(self.menu)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.gridLayout_2.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(10, -1, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame = QtWidgets.QLabel(self.gridLayoutWidget)
        self.frame.setStyleSheet("background-color: black;border-top-left-radius : 25px;border-bottom-right-radius :25px;")
        self.frame.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setLineWidth(5)
        self.frame.setMidLineWidth(3)
        self.frame.setText("")
        self.frame.setObjectName("frame")
        self.verticalLayout_3.addWidget(self.frame)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 50, -1, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.status = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("STIXVariants")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.status.setFont(font)
        self.status.setStyleSheet("")
        self.status.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.status.setObjectName("status")
        self.verticalLayout_4.addWidget(self.status)
        self.horizontalLayout_3.addLayout(self.verticalLayout_4)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setContentsMargins(-1, -1, 10, -1)
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setItalic(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.name = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setItalic(True)
        self.name.setFont(font)
        self.name.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.name.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.name.setAlignment(QtCore.Qt.AlignCenter)
        self.name.setObjectName("name")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.name)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setItalic(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.id_num = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setItalic(True)
        self.id_num.setFont(font)
        self.id_num.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.id_num.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.id_num.setAlignment(QtCore.Qt.AlignCenter)
        self.id_num.setObjectName("id_num")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.id_num)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setItalic(True)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.date = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setItalic(True)
        self.date.setFont(font)
        self.date.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.date.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.date.setAlignment(QtCore.Qt.AlignCenter)
        self.date.setObjectName("date")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.date)
        self.horizontalLayout_3.addLayout(self.formLayout)
        self.horizontalLayout_3.setStretch(0, 2)
        self.horizontalLayout_3.setStretch(1, 4)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.verticalLayout_3.setStretch(0, 5)
        self.verticalLayout_3.setStretch(1, 3)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 0, 1, 1, 1)
        self.gridLayout_2.setColumnStretch(0, 1)
        self.gridLayout_2.setColumnStretch(1, 3)
        self.gridLayoutWidget.raise_()
        self.label_8.raise_()
        Index_UI.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Index_UI)
        self.statusbar.setObjectName("statusbar")
        Index_UI.setStatusBar(self.statusbar)

        self.retranslateUi(Index_UI)
        QtCore.QMetaObject.connectSlotsByName(Index_UI)

    def retranslateUi(self, Index_UI):
        _translate = QtCore.QCoreApplication.translate
        Index_UI.setWindowTitle(_translate("Index_UI", "FRASI Manager"))
        self.label_8.setText(_translate("Index_UI", "FRASI Manager"))
        self.label.setText(_translate("Index_UI", "Menu"))
        self.menu.headerItem().setText(0, _translate("Index_UI", "menu"))
        __sortingEnabled = self.menu.isSortingEnabled()
        self.menu.setSortingEnabled(False)
        self.menu.topLevelItem(0).setText(0, _translate("Index_UI", "Face Recognition"))
        self.menu.topLevelItem(0).child(0).setText(0, _translate("Index_UI", "人脸检测"))
        self.menu.topLevelItem(0).child(1).setText(0, _translate("Index_UI", "人脸识别"))
        self.menu.topLevelItem(0).child(2).setText(0, _translate("Index_UI", "人脸考勤"))
        self.menu.topLevelItem(0).child(3).setText(0, _translate("Index_UI", "人脸检索"))
        self.menu.topLevelItem(0).child(4).setText(0, _translate("Index_UI", "单脸注册"))
        self.menu.topLevelItem(0).child(5).setText(0, _translate("Index_UI", "多脸注册"))
        self.menu.topLevelItem(0).child(6).setText(0, _translate("Index_UI", "身份证注册"))
        self.menu.topLevelItem(1).setText(0, _translate("Index_UI", "Speech Interaction"))
        self.menu.topLevelItem(1).child(0).setText(0, _translate("Index_UI", "语音识别"))
        self.menu.topLevelItem(1).child(1).setText(0, _translate("Index_UI", "语音检索"))
        self.menu.topLevelItem(1).child(2).setText(0, _translate("Index_UI", "语音考勤"))
        self.menu.topLevelItem(1).child(3).setText(0, _translate("Index_UI", "语音注册"))
        self.menu.topLevelItem(2).setText(0, _translate("Index_UI", "Data Management"))
        self.menu.topLevelItem(2).child(0).setText(0, _translate("Index_UI", "数据导出"))
        self.menu.topLevelItem(2).child(1).setText(0, _translate("Index_UI", "数据导入"))
        self.menu.topLevelItem(2).child(2).setText(0, _translate("Index_UI", "统计查看"))
        self.menu.topLevelItem(3).setText(0, _translate("Index_UI", "System Option"))
        self.menu.topLevelItem(3).child(0).setText(0, _translate("Index_UI", "参数配置"))
        self.menu.setSortingEnabled(__sortingEnabled)
        self.status.setText(_translate("Index_UI", "考勤中..."))
        self.label_2.setText(_translate("Index_UI", "Name"))
        self.name.setText(_translate("Index_UI", "郭高余"))
        self.label_3.setText(_translate("Index_UI", "ID"))
        self.id_num.setText(_translate("Index_UI", "201610414206"))
        self.label_4.setText(_translate("Index_UI", "Date"))
        self.date.setText(_translate("Index_UI", "2018-10-05 20:20:30"))

